wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.2
    start_time: 1661519192.784602
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 77
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 77
      3:
      - 1
      - 13
      - 23
      4: 3.9.2
      5: 0.13.1
      8:
      - 1
      - 3
      - 5
